/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 03-25-2026
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
global class Demo {  // Violates AvoidGlobalModifier
  
    public void excessiveParamsMethod(String param1, String param2, String param3, String param4, String param5) { 
       // Violates ExcessiveParameterList (more than 4 params)
       String[] params = new String[] {param1, param2, param3, param4, param5};
       for (String param : params) {
           System.debug('Parameterss: ' + param);
           System.debug('Excessive Parameters Testing!!');
       }
    }

    public void hardCodedIdMethod() {
        String hardcodedId = '0019000000XXXXXXX';  // Violates AvoidHardcodingId
        // Account acc = [SELECT Id, Name FROM Account WHERE Id = :hardcodedId WITH SECURITY_ENFORCED];
        Account acc = [SELECT Id, Name FROM Account WHERE Id = :hardcodedId];
        System.debug('Account'+acc);
   } 

    public void deeplyNestedIfMethod(Integer value) {  
        // Violates AvoidDeeplyNestedIfStmts (nested more than 4 levels)
        if (value > 0) {
            if (value > 10) {
                if (value > 20) {
                    if (value > 30) {
                        System.debug('Too much nesting181 Testing!!');
                        if(value>40){
                            System.debug('Nesting is too much 1 Testing!!');
                        }
                        else {
                            System.debug('Else Statement');
                        }
                    }
                    else{
                        System.debug('Else Statement');
                    }
                }
            }
        }
    }

    public void sampleTestMethod(Integer num) { 
        if (num > 5) {
            System.debug('Num is greater than 5');
        }
        System.debug('Testing new method Bro');
    }

    public void soqlInjection(String userInput) {  
        // Violates ApexSOQLInjection (Unsafe SOQL query)
        String query = 'SELECT Id, Name FROM Account WHERE Name LIKE \'%' + userInput + '%\'';
        List<Account> accounts = Database.query(query);
       System.debug(accounts);
    }
}
